#!/bin/bash

MYSQL_PASSWORD=$1
HOST=$2
DB_PASSWORD=$3
DATABASE=$4

mysql -uroot -p$MYSQL_PASSWORD -h$HOST -e "GRANT ALL PRIVILEGES ON $DATABASE.* TO '$DATABASE'@'localhost' IDENTIFIED BY '$DB_PASSWORD'"

mysql -uroot -p$MYSQL_PASSWORD -h$HOST -e "GRANT ALL PRIVILEGES ON $DATABASE.* TO '$DATABASE'@'%' IDENTIFIED BY '$DB_PASSWORD'"
